// Author: Gianfranco Tassielli

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// rAPPNUWSTrAPPNUWSMain                                                      //
//                                                                            //
// Begin_Html <!--
/*-->

Description:
<p>
Main task. This task does common initialization for all the tasks.
</p>

<!--*/
// --> End_Html
//                                                                            //
// The event methods have been written by Gianfranco Tassielli.               //
//                                                                            //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

/* Generated header file containing necessary includes                        */
#include "generated/rAPPNUWSTrAPPNUWSMainGeneratedIncludes.h"

////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "generated/rAPPNUWSAnalyzer.h"
#include "tasks/rAPPNUWSTrAPPNUWSMain.h"
#include "ROMEiostream.h"

// uncomment if you want to include headers of all folders
//#include "rAPPNUWSAllFolders.h"


ClassImp(rAPPNUWSTrAPPNUWSMain)

//______________________________________________________________________________
void rAPPNUWSTrAPPNUWSMain::Init()
{
}

//______________________________________________________________________________
void rAPPNUWSTrAPPNUWSMain::BeginOfRun() {



}

//______________________________________________________________________________
void rAPPNUWSTrAPPNUWSMain::Event()
{
}

//______________________________________________________________________________
void rAPPNUWSTrAPPNUWSMain::EndOfRun()
{
}

//______________________________________________________________________________
void rAPPNUWSTrAPPNUWSMain::Terminate()
{
}

